// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uiot.proto

package uiot

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Meta contains human-readable information about a device. Name, type of device,
// and room it is located in
type Meta struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Room                 uint32   `protobuf:"varint,2,opt,name=room,proto3" json:"room,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{0}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Meta) GetRoom() uint32 {
	if m != nil {
		return m.Room
	}
	return 0
}

func (m *Meta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Param messages represent valid parameters for a given function.
// Contains mininum and maximum values the parameter can take.
type Param struct {
	Min                  uint32   `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  uint32   `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{1}
}

func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (m *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(m, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetMin() uint32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Param) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

// Func messages represent individual functions a device can perform.
// Contains an ID, human-readable name, and list of parameters.
type Func struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params               []*Param `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Func) Reset()         { *m = Func{} }
func (m *Func) String() string { return proto.CompactTextString(m) }
func (*Func) ProtoMessage()    {}
func (*Func) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{2}
}

func (m *Func) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Func.Unmarshal(m, b)
}
func (m *Func) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Func.Marshal(b, m, deterministic)
}
func (m *Func) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Func.Merge(m, src)
}
func (m *Func) XXX_Size() int {
	return xxx_messageInfo_Func.Size(m)
}
func (m *Func) XXX_DiscardUnknown() {
	xxx_messageInfo_Func.DiscardUnknown(m)
}

var xxx_messageInfo_Func proto.InternalMessageInfo

func (m *Func) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Func) GetParams() []*Param {
	if m != nil {
		return m.Params
	}
	return nil
}

// DevInfo message are sent when a new device is connecting to the network.
// Contains a device's identifying information and all of the functions it performs.
type DevInfo struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Funcs                []*Func  `protobuf:"bytes,4,rep,name=funcs,proto3" json:"funcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevInfo) Reset()         { *m = DevInfo{} }
func (m *DevInfo) String() string { return proto.CompactTextString(m) }
func (*DevInfo) ProtoMessage()    {}
func (*DevInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{3}
}

func (m *DevInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevInfo.Unmarshal(m, b)
}
func (m *DevInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevInfo.Marshal(b, m, deterministic)
}
func (m *DevInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevInfo.Merge(m, src)
}
func (m *DevInfo) XXX_Size() int {
	return xxx_messageInfo_DevInfo.Size(m)
}
func (m *DevInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DevInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DevInfo proto.InternalMessageInfo

func (m *DevInfo) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *DevInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DevInfo) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *DevInfo) GetFuncs() []*Func {
	if m != nil {
		return m.Funcs
	}
	return nil
}

// FuncCall is used when calling functions on a remote device. Provides the name
// and parameter values, set by the caller.
type FuncCall struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params               []uint32 `protobuf:"varint,2,rep,packed,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuncCall) Reset()         { *m = FuncCall{} }
func (m *FuncCall) String() string { return proto.CompactTextString(m) }
func (*FuncCall) ProtoMessage()    {}
func (*FuncCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{4}
}

func (m *FuncCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncCall.Unmarshal(m, b)
}
func (m *FuncCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncCall.Marshal(b, m, deterministic)
}
func (m *FuncCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncCall.Merge(m, src)
}
func (m *FuncCall) XXX_Size() int {
	return xxx_messageInfo_FuncCall.Size(m)
}
func (m *FuncCall) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncCall.DiscardUnknown(m)
}

var xxx_messageInfo_FuncCall proto.InternalMessageInfo

func (m *FuncCall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FuncCall) GetParams() []uint32 {
	if m != nil {
		return m.Params
	}
	return nil
}

// StatusEntry contains one component reporting a device's state
// Preview for what multi-type support may look like in the future
type StatusEntry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusEntry) Reset()         { *m = StatusEntry{} }
func (m *StatusEntry) String() string { return proto.CompactTextString(m) }
func (*StatusEntry) ProtoMessage()    {}
func (*StatusEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{5}
}

func (m *StatusEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusEntry.Unmarshal(m, b)
}
func (m *StatusEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusEntry.Marshal(b, m, deterministic)
}
func (m *StatusEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusEntry.Merge(m, src)
}
func (m *StatusEntry) XXX_Size() int {
	return xxx_messageInfo_StatusEntry.Size(m)
}
func (m *StatusEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StatusEntry proto.InternalMessageInfo

func (m *StatusEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StatusEntry) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StatusEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// Statuses are used to report arbitrary information about remote device states.
type Status struct {
	Entries              []*StatusEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{6}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetEntries() []*StatusEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

// FuncRet represents function return values. Empty for now, allowing the ability
// to expand in the future
type FuncRet struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuncRet) Reset()         { *m = FuncRet{} }
func (m *FuncRet) String() string { return proto.CompactTextString(m) }
func (*FuncRet) ProtoMessage()    {}
func (*FuncRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{7}
}

func (m *FuncRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncRet.Unmarshal(m, b)
}
func (m *FuncRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncRet.Marshal(b, m, deterministic)
}
func (m *FuncRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncRet.Merge(m, src)
}
func (m *FuncRet) XXX_Size() int {
	return xxx_messageInfo_FuncRet.Size(m)
}
func (m *FuncRet) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncRet.DiscardUnknown(m)
}

var xxx_messageInfo_FuncRet proto.InternalMessageInfo

// Nothing represents nothing
type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{8}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Meta)(nil), "Meta")
	proto.RegisterType((*Param)(nil), "Param")
	proto.RegisterType((*Func)(nil), "Func")
	proto.RegisterType((*DevInfo)(nil), "DevInfo")
	proto.RegisterType((*FuncCall)(nil), "FuncCall")
	proto.RegisterType((*StatusEntry)(nil), "StatusEntry")
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*FuncRet)(nil), "FuncRet")
	proto.RegisterType((*Nothing)(nil), "Nothing")
}

func init() { proto.RegisterFile("uiot.proto", fileDescriptor_761f8d2c87cd1351) }

var fileDescriptor_761f8d2c87cd1351 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x5f, 0x8b, 0xd3, 0x40,
	0x14, 0xc5, 0x93, 0x36, 0x7f, 0x6f, 0x5b, 0x90, 0x41, 0x24, 0x56, 0x91, 0x74, 0x1e, 0xa4, 0x20,
	0x0c, 0x52, 0xc1, 0x07, 0x1f, 0x6b, 0x55, 0x44, 0x14, 0x1d, 0x3f, 0xc1, 0x6c, 0x3b, 0xdd, 0x0d,
	0x34, 0x33, 0x61, 0x72, 0x53, 0xb6, 0x5f, 0x62, 0x3f, 0xf3, 0x32, 0x93, 0x49, 0x77, 0x0b, 0x7d,
	0x3b, 0x73, 0x92, 0x39, 0xf7, 0x77, 0x4f, 0x02, 0xd0, 0x55, 0x1a, 0x59, 0x63, 0x34, 0x6a, 0xba,
	0x86, 0xe8, 0xb7, 0x44, 0x41, 0x08, 0x44, 0x78, 0x6a, 0x64, 0x11, 0x96, 0xe1, 0x72, 0xc6, 0x9d,
	0xb6, 0x9e, 0xd1, 0xba, 0x2e, 0x46, 0xbd, 0x67, 0xb5, 0xf5, 0x94, 0xa8, 0x65, 0x31, 0x2e, 0xc3,
	0x65, 0xce, 0x9d, 0xa6, 0x1f, 0x20, 0xfe, 0x2b, 0x8c, 0xa8, 0xc9, 0x0b, 0x18, 0xd7, 0x95, 0xf2,
	0x19, 0x56, 0x3a, 0x47, 0xdc, 0xfb, 0x04, 0x2b, 0xe9, 0x17, 0x88, 0xbe, 0x77, 0x6a, 0x7b, 0x0e,
	0x0a, 0x9f, 0x82, 0xc8, 0x3b, 0x48, 0x1a, 0x1b, 0xd4, 0x16, 0xa3, 0x72, 0xbc, 0x9c, 0xac, 0x12,
	0xe6, 0x72, 0xb9, 0x77, 0x69, 0x05, 0xe9, 0x46, 0x1e, 0x7f, 0xaa, 0xbd, 0xb6, 0xd7, 0x1b, 0x6d,
	0x70, 0xe0, 0xb5, 0xda, 0x7a, 0x62, 0xb7, 0x33, 0x6e, 0x5a, 0xce, 0x9d, 0x26, 0xaf, 0x21, 0xaa,
	0x25, 0x0a, 0xc7, 0x3b, 0x59, 0xc5, 0xcc, 0x2e, 0xcb, 0x9d, 0x45, 0xde, 0x40, 0xbc, 0xef, 0xd4,
	0xb6, 0x2d, 0x22, 0x37, 0x2c, 0x66, 0x96, 0x8b, 0xf7, 0x1e, 0xfd, 0x0c, 0x99, 0x3d, 0x7e, 0x15,
	0x87, 0xc3, 0x55, 0xd4, 0x57, 0x17, 0xa8, 0xb3, 0x33, 0xe2, 0x2f, 0x98, 0xfc, 0x47, 0x81, 0x5d,
	0xfb, 0x4d, 0xa1, 0x39, 0x5d, 0xbd, 0x3a, 0x54, 0xed, 0x31, 0x5d, 0xd5, 0x2f, 0x21, 0x3e, 0x8a,
	0x43, 0xd7, 0xf7, 0x3a, 0xe5, 0xfd, 0x81, 0x7e, 0x84, 0xa4, 0x0f, 0x23, 0xef, 0x21, 0x95, 0x0a,
	0x4d, 0x25, 0xdb, 0x22, 0x74, 0xb4, 0x53, 0xf6, 0x6c, 0x0c, 0x1f, 0x1e, 0xd2, 0x1c, 0x52, 0xb7,
	0x85, 0x44, 0x2b, 0xff, 0x68, 0xbc, 0xab, 0xd4, 0xed, 0xea, 0x21, 0x84, 0x64, 0x23, 0x8f, 0xd5,
	0x56, 0x92, 0x05, 0xe4, 0x6b, 0xad, 0xb1, 0x45, 0x23, 0x1a, 0x92, 0x31, 0x5f, 0xe7, 0xfc, 0xac,
	0x68, 0x40, 0x16, 0x90, 0xd9, 0xb5, 0xdd, 0x57, 0xca, 0xd9, 0xd0, 0xc2, 0x3c, 0x63, 0x43, 0x72,
	0x40, 0x4a, 0xc8, 0x7f, 0x48, 0xf4, 0x6c, 0x19, 0xf3, 0x73, 0xe6, 0xa9, 0x87, 0xa2, 0x01, 0x79,
	0x0b, 0xd1, 0xbf, 0xae, 0xc2, 0x8b, 0x11, 0xfe, 0x35, 0x1a, 0xdc, 0x24, 0xee, 0xe7, 0xfb, 0xf4,
	0x18, 0x00, 0x00, 0xff, 0xff, 0x38, 0x20, 0x2d, 0x89, 0x8a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeviceClient is the client API for Device service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceClient interface {
	// Send our information to a remote device, and get theirs in return
	Bootstrap(ctx context.Context, in *DevInfo, opts ...grpc.CallOption) (*DevInfo, error)
	// call a function on a remote device
	CallFunc(ctx context.Context, in *FuncCall, opts ...grpc.CallOption) (*FuncRet, error)
	// request status from a remote device
	GetStatus(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Status, error)
	// tell a remote device that we are quitting, and to remove us from their network
	Quit(ctx context.Context, in *DevInfo, opts ...grpc.CallOption) (*Nothing, error)
}

type deviceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceClient(cc grpc.ClientConnInterface) DeviceClient {
	return &deviceClient{cc}
}

func (c *deviceClient) Bootstrap(ctx context.Context, in *DevInfo, opts ...grpc.CallOption) (*DevInfo, error) {
	out := new(DevInfo)
	err := c.cc.Invoke(ctx, "/Device/Bootstrap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) CallFunc(ctx context.Context, in *FuncCall, opts ...grpc.CallOption) (*FuncRet, error) {
	out := new(FuncRet)
	err := c.cc.Invoke(ctx, "/Device/CallFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetStatus(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/Device/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) Quit(ctx context.Context, in *DevInfo, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/Device/Quit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServer is the server API for Device service.
type DeviceServer interface {
	// Send our information to a remote device, and get theirs in return
	Bootstrap(context.Context, *DevInfo) (*DevInfo, error)
	// call a function on a remote device
	CallFunc(context.Context, *FuncCall) (*FuncRet, error)
	// request status from a remote device
	GetStatus(context.Context, *Nothing) (*Status, error)
	// tell a remote device that we are quitting, and to remove us from their network
	Quit(context.Context, *DevInfo) (*Nothing, error)
}

// UnimplementedDeviceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceServer struct {
}

func (*UnimplementedDeviceServer) Bootstrap(ctx context.Context, req *DevInfo) (*DevInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bootstrap not implemented")
}
func (*UnimplementedDeviceServer) CallFunc(ctx context.Context, req *FuncCall) (*FuncRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallFunc not implemented")
}
func (*UnimplementedDeviceServer) GetStatus(ctx context.Context, req *Nothing) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (*UnimplementedDeviceServer) Quit(ctx context.Context, req *DevInfo) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quit not implemented")
}

func RegisterDeviceServer(s *grpc.Server, srv DeviceServer) {
	s.RegisterService(&_Device_serviceDesc, srv)
}

func _Device_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device/Bootstrap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Bootstrap(ctx, req.(*DevInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_CallFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FuncCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).CallFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device/CallFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).CallFunc(ctx, req.(*FuncCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetStatus(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device/Quit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Quit(ctx, req.(*DevInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Device_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Device",
	HandlerType: (*DeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bootstrap",
			Handler:    _Device_Bootstrap_Handler,
		},
		{
			MethodName: "CallFunc",
			Handler:    _Device_CallFunc_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Device_GetStatus_Handler,
		},
		{
			MethodName: "Quit",
			Handler:    _Device_Quit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uiot.proto",
}
