// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uiot.proto

package uiot

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Meta contains human-readable information about a device. Name, type of device,
// and room it is located in
type Meta struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Room                 uint32   `protobuf:"varint,2,opt,name=room,proto3" json:"room,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{0}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Meta) GetRoom() uint32 {
	if m != nil {
		return m.Room
	}
	return 0
}

func (m *Meta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Param messages represent valid parameters for a given function.
// Contains mininum and maximum values the parameter can take.
type Param struct {
	Min                  uint32   `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  uint32   `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{1}
}

func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (m *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(m, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetMin() uint32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Param) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

// Func messages represent individual functions a device can perform.
// Contains an ID, human-readable name, and list of parameters.
type Func struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params               []*Param `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Func) Reset()         { *m = Func{} }
func (m *Func) String() string { return proto.CompactTextString(m) }
func (*Func) ProtoMessage()    {}
func (*Func) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{2}
}

func (m *Func) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Func.Unmarshal(m, b)
}
func (m *Func) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Func.Marshal(b, m, deterministic)
}
func (m *Func) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Func.Merge(m, src)
}
func (m *Func) XXX_Size() int {
	return xxx_messageInfo_Func.Size(m)
}
func (m *Func) XXX_DiscardUnknown() {
	xxx_messageInfo_Func.DiscardUnknown(m)
}

var xxx_messageInfo_Func proto.InternalMessageInfo

func (m *Func) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Func) GetParams() []*Param {
	if m != nil {
		return m.Params
	}
	return nil
}

// DevInfo message are sent when a new device is connecting to the network.
// Contains a device's identifying information and all of the functions it performs.
type DevInfo struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Funcs                []*Func  `protobuf:"bytes,4,rep,name=funcs,proto3" json:"funcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevInfo) Reset()         { *m = DevInfo{} }
func (m *DevInfo) String() string { return proto.CompactTextString(m) }
func (*DevInfo) ProtoMessage()    {}
func (*DevInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{3}
}

func (m *DevInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevInfo.Unmarshal(m, b)
}
func (m *DevInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevInfo.Marshal(b, m, deterministic)
}
func (m *DevInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevInfo.Merge(m, src)
}
func (m *DevInfo) XXX_Size() int {
	return xxx_messageInfo_DevInfo.Size(m)
}
func (m *DevInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DevInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DevInfo proto.InternalMessageInfo

func (m *DevInfo) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *DevInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DevInfo) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *DevInfo) GetFuncs() []*Func {
	if m != nil {
		return m.Funcs
	}
	return nil
}


// FuncCall is used when calling functions on a remote device. Provides the name
// and parameter values, set by the caller.
type FuncCall struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params               []uint32 `protobuf:"varint,2,rep,packed,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuncCall) Reset()         { *m = FuncCall{} }
func (m *FuncCall) String() string { return proto.CompactTextString(m) }
func (*FuncCall) ProtoMessage()    {}
func (*FuncCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{4}
}

func (m *FuncCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncCall.Unmarshal(m, b)
}
func (m *FuncCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncCall.Marshal(b, m, deterministic)
}
func (m *FuncCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncCall.Merge(m, src)
}
func (m *FuncCall) XXX_Size() int {
	return xxx_messageInfo_FuncCall.Size(m)
}
func (m *FuncCall) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncCall.DiscardUnknown(m)
}

var xxx_messageInfo_FuncCall proto.InternalMessageInfo

func (m *FuncCall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FuncCall) GetParams() []uint32 {
	if m != nil {
		return m.Params
	}
	return nil
}

// Err represents an error message. Simply a string. Empty string when there is no
// error.
type Err struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Err) Reset()         { *m = Err{} }
func (m *Err) String() string { return proto.CompactTextString(m) }
func (*Err) ProtoMessage()    {}
func (*Err) Descriptor() ([]byte, []int) {
	return fileDescriptor_761f8d2c87cd1351, []int{5}
}

func (m *Err) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Err.Unmarshal(m, b)
}
func (m *Err) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Err.Marshal(b, m, deterministic)
}
func (m *Err) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Err.Merge(m, src)
}
func (m *Err) XXX_Size() int {
	return xxx_messageInfo_Err.Size(m)
}
func (m *Err) XXX_DiscardUnknown() {
	xxx_messageInfo_Err.DiscardUnknown(m)
}

var xxx_messageInfo_Err proto.InternalMessageInfo

func (m *Err) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Meta)(nil), "Meta")
	proto.RegisterType((*Param)(nil), "Param")
	proto.RegisterType((*Func)(nil), "Func")
	proto.RegisterType((*DevInfo)(nil), "DevInfo")
	proto.RegisterType((*FuncCall)(nil), "FuncCall")
	proto.RegisterType((*Err)(nil), "Err")
}

func init() { proto.RegisterFile("uiot.proto", fileDescriptor_761f8d2c87cd1351) }

var fileDescriptor_761f8d2c87cd1351 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0x9b, 0x66, 0x93, 0xaf, 0x99, 0x52, 0xf8, 0xd8, 0x83, 0xc6, 0x8a, 0x12, 0xf7, 0x14,
	0x10, 0xf6, 0x10, 0xc1, 0x83, 0xc7, 0xda, 0x0a, 0x0a, 0x82, 0xec, 0x3f, 0x58, 0xd3, 0xad, 0x04,
	0x9a, 0x6c, 0xd8, 0x6c, 0x8a, 0xfe, 0x7b, 0x99, 0x69, 0x1a, 0x11, 0xbc, 0x3d, 0x79, 0x60, 0xde,
	0x79, 0x27, 0x0b, 0xd0, 0x57, 0xd6, 0xcb, 0xd6, 0x59, 0x6f, 0xc5, 0x0a, 0xd8, 0xab, 0xf1, 0x9a,
	0x73, 0x60, 0xfe, 0xab, 0x35, 0x69, 0x90, 0x05, 0xf9, 0x42, 0x11, 0xa3, 0x73, 0xd6, 0xd6, 0xe9,
	0xf4, 0xe8, 0x90, 0xd1, 0x35, 0xba, 0x36, 0x69, 0x98, 0x05, 0x79, 0xa2, 0x88, 0xc5, 0x2d, 0x44,
	0x6f, 0xda, 0xe9, 0x9a, 0xff, 0x87, 0xb0, 0xae, 0x9a, 0x21, 0x03, 0x91, 0x8c, 0xfe, 0x1c, 0x12,
	0x10, 0xc5, 0x03, 0xb0, 0xa7, 0xbe, 0x29, 0xc7, 0xa0, 0xe0, 0x27, 0x88, 0x5f, 0x43, 0xdc, 0x62,
	0x50, 0x97, 0x4e, 0xb3, 0x30, 0x9f, 0x17, 0xb1, 0xa4, 0x5c, 0x35, 0x58, 0x51, 0xc1, 0xbf, 0xb5,
	0x39, 0x3c, 0x37, 0x3b, 0x8b, 0xe3, 0xad, 0x75, 0xfe, 0xd4, 0x17, 0x19, 0x9d, 0xde, 0x6e, 0x1d,
	0x6d, 0x4b, 0x14, 0x31, 0xbf, 0x00, 0x56, 0x1b, 0xaf, 0xa9, 0xef, 0xbc, 0x88, 0x24, 0x1e, 0xab,
	0x48, 0xf1, 0x4b, 0x88, 0x76, 0x7d, 0x53, 0x76, 0x29, 0xa3, 0x65, 0x91, 0xc4, 0x5e, 0xea, 0xe8,
	0xc4, 0x3d, 0xcc, 0xf0, 0xf3, 0x51, 0xef, 0xf7, 0x7f, 0x56, 0x3d, 0xfb, 0x55, 0x75, 0x31, 0x56,
	0x3c, 0x87, 0x70, 0xe3, 0x1c, 0xdd, 0xdd, 0x7d, 0x0c, 0x13, 0x88, 0xc5, 0x0b, 0xc4, 0x6b, 0x73,
	0xa8, 0x4a, 0xc3, 0x6f, 0x20, 0x59, 0x59, 0xeb, 0x3b, 0xef, 0x74, 0xcb, 0x67, 0x72, 0xb8, 0x68,
	0x39, 0x92, 0x98, 0xf0, 0x2b, 0x98, 0xe1, 0x66, 0xfa, 0x51, 0x89, 0x3c, 0x15, 0x59, 0x32, 0xb9,
	0x71, 0x4e, 0x4c, 0xde, 0x63, 0x7a, 0xbb, 0xbb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xda,
	0x50, 0xe9, 0xc9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeviceClient is the client API for Device service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceClient interface {
	// Send our information to a remote device, and get theirs in return
	Bootstrap(ctx context.Context, in *DevInfo, opts ...grpc.CallOption) (*DevInfo, error)
	CallFunc(ctx context.Context, in *FuncCall, opts ...grpc.CallOption) (*Err, error)
}

type deviceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceClient(cc grpc.ClientConnInterface) DeviceClient {
	return &deviceClient{cc}
}

func (c *deviceClient) Bootstrap(ctx context.Context, in *DevInfo, opts ...grpc.CallOption) (*DevInfo, error) {
	out := new(DevInfo)
	err := c.cc.Invoke(ctx, "/Device/Bootstrap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) CallFunc(ctx context.Context, in *FuncCall, opts ...grpc.CallOption) (*Err, error) {
	out := new(Err)
	err := c.cc.Invoke(ctx, "/Device/CallFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServer is the server API for Device service.
type DeviceServer interface {
	// Send our information to a remote device, and get theirs in return
	Bootstrap(context.Context, *DevInfo) (*DevInfo, error)
	CallFunc(context.Context, *FuncCall) (*Err, error)
}

// UnimplementedDeviceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceServer struct {
}

func (*UnimplementedDeviceServer) Bootstrap(ctx context.Context, req *DevInfo) (*DevInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bootstrap not implemented")
}

func (*UnimplementedDeviceServer) CallFunc(ctx context.Context, req *FuncCall) (*Err, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallFunc not implemented")
}

func RegisterDeviceServer(s *grpc.Server, srv DeviceServer) {
	s.RegisterService(&_Device_serviceDesc, srv)
}

func _Device_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device/Bootstrap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Bootstrap(ctx, req.(*DevInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_CallFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FuncCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).CallFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Device/CallFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).CallFunc(ctx, req.(*FuncCall))
	}
	return interceptor(ctx, in, info, handler)
}

var _Device_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Device",
	HandlerType: (*DeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bootstrap",
			Handler:    _Device_Bootstrap_Handler,
		},
		{
			MethodName: "CallFunc",
			Handler:    _Device_CallFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uiot.proto",
}
